#!/usr/bin/env bash
# Update the list of available packages and install nginx
apt-get -y update
apt-get -y install nginx

ufw app list
ufw allow 'Nginx HTTP'

mkdir -p /var/www/html
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html

service nginx restart

