#!/usr/bin/env bash
# Script to install and configure HAProxy on a server

# Update package list
sudo apt-get update

# Install HAProxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.*

# Configure HAProxy
config_file="/etc/haproxy/haproxy.cfg"
frontend="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web"
servera="server 264821-web-01 34.224.63.208:80 check"
serverb="server 264821-web-02 100.26.175.90:80 check"
backend="backend web\n\tbalance roundrobin\n\t$servera\n\t$serverb"

sudo sed -i "$ a $frontend" $config_file
sudo sed -i "$ a $backend" $config_file

# Restart HAProxy
sudo service haproxy restart

