#!/usr/bin/env bash
# bash script that displays the content of the file /etc/passwd
# only display the  username, user id, Home directory path for the user

while read -r line;do
	echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
