#!/usr/bin/env bash
# bash script that display "Best School" 10 times
# displays "bad luck" for the  loop iteration 4
# displays "good luck" for the loop iteration 8
# displays "Best School" for the other iterations

i=0
while [ $i -lt 10 ];do
  if [ $i -eq 3 ];then
	  echo "bad luck"
  elif [ $i -eq 7 ];then
	  echo "good luck"
  else
	  echo "Best School"
  fi
  (( i++ ))
done
